### ISSUE TITLE
YesScript prevents bookmarklet function on blank page

### ISSUE THREAD

**Issue by elrucio** [JasonBarnabe/yesscript#10]
With either about:newtab (default) or about:blank as start and new tab pages, YesScript prevents a javascript bookmarklet from working. (In my case, I frequently use the Quix utility for quick lookups.)

Without YesScript, the bookmarklet works when about:blank is loaded but not about:newtab.

With YesScript, again, the bookmarklet does not work with either about:blank or about:newtab (blank or with history and ads. Nor does it work with data:text/html,SomeText. It does, however, work with a simple blank html page loaded from the desktop (file:///Users/~/Desktop/blank.html).

I don't know the inner workings of either Firefox or YesScript, but I've seen it mentioned that with about:newtab, Firefox does not load its javascript processor (or something). With about:blank and data:~, it would seem that whatever calls YesScript to allow javascript doesn't happen. With the simplest of html files, that call does happen.

Perhaps YesScript is jumping in too early?

**Comment by JasonBarnabe** [comment]
YesScript is no longer being developed.
