### ISSUE TITLE
YesScript causes Yahoo email into plain text MIME format, unrecoverable

### ISSUE THREAD

**Issue by crew4food** [JasonBarnabe/yesscript#11]
Attempted to use YesScript to cure unresponsive script delays in Yahoo mail. But turning off scripts forced email into plain text MIME format.  Deleted Yahoo from YesScript sites, but still can't select new format. Uninstalled YesScript, but still no luck Uninstalled/re-installed Firefox, but still can't get new format. Help!
P.S.:  New format comes up fine in Internet Explorer

**Comment by JasonBarnabe** [comment]
YesScript is no longer being developed.
