### ISSUE TITLE
Firefox crashes when addons YesScript and Zotero are both installed

### ISSUE THREAD

**Issue by antoneliasson** [JasonBarnabe/yesscript#13]
Steps to reproduce (tested with a blank profile):

1. Install Zotero for Firefox 4.0.29.16 from https://www.zotero.org/download/
2. Install YesScript 2.2 from addons.mozilla.org
3. Restart Firefox
4. Go to www.google.com
5. Click the YesScript blacklist button
6. Press F5 to refresh page
7. Firefox crashes.

Platform: Ubuntu 16.04 64-bit. Firefox 50.1.0.

**Comment by antoneliasson** [comment]
Cross-reported to Zotero as https://forums.zotero.org/discussion/63733/854545803-firefox-crashes-when-addons-yesscript-and-zotero-are-both-installed

**Comment by antoneliasson** [comment]
Firefox bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1328861

**Comment by JasonBarnabe** [comment]
YesScript is no longer being developed.
