### ISSUE TITLE
YesScript breaks Firefox Developer Edition's JSONView

### ISSUE THREAD

**Issue by timothykim** [JasonBarnabe/yesscript#14]
Steps to reproduce:

1. Install Firefox Developer Edition
2. Visit http://httpbin.org/get to confirm that the JSON view is working
3. Install YesScript
4. Restart and visit http://httpbin.org/get to see the raw JSON response instead of JSON view UI.

Screenshot:

Expected (no YesScript installed): https://i.imgur.com/G4hbjaO.png

Expected (with YesScript installed): https://i.imgur.com/L3DNC0f.png

**Comment by JasonBarnabe** [comment]
YesScript is no longer being developed.
