### ISSUE TITLE
WebExtension

### ISSUE THREAD

**Issue by KAMiKAZOW** [JasonBarnabe/yesscript#16]
YesScript is a "Legacy" extension and will stop working in Firefox 57 (currently in beta). A WebExtension version would be great.

**Comment by JasonBarnabe** [comment]
I don't intend on making any more changes. If someone would like to convert the extension, go right ahead.

**Comment by moggers87** [comment]
https://github.com/log69/yesscript2 is a webextension rewrite of YesScript (n.b. I haven't tried it yet)
