### ISSUE TITLE
PaleMoon 25 support

### ISSUE THREAD

**Issue by JasonBarnabe** [JasonBarnabe/yesscript#9]
From e-mail:

YesScript 2.0 FireFox extension stops working in PaleMoon 25.0 (it used to work fine in PaleMoon 24)
Well, probably it is work, but the YesScript icon is not in Customize icons list any longer and the icon could not be put to any browser's bar.

PaleMoon developers changed something that is described here:
https://forum.palemoon.org/viewtopic.php?f=24&t=5932

Is it possible to modify the extension that will allow to use it in PaleMoon again?

**Comment by JasonBarnabe** [comment]
https://github.com/JasonBarnabe/yesscript/commit/d057349af299416b7d609d4e127a9fd8f20df1a1

**Comment by dr-st** [comment]
Thank you! 


     On Wednesday, April 8, 2015 6:08 PM, Jason Barnabe <notifications@github.com> wrote:
   

 Closed #9.—
